spring:
  datasource:
    url: jdbc:postgresql://db:5432/auth_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: your-256-bit-secret-key-for-jwt
  expiration: 86400000
notification:
  service:
    url: http://notification-service:8081/api/notifications/send
logging:
  level:
    com.krainet: DEBUG