CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(100) NOT NULL,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       first_name VARCHAR(50),
                       last_name VARCHAR(50),
                       role VARCHAR(20) NOT NULL
);

INSERT INTO users (username, password, email, first_name, last_name, role)
VALUES
    ('admin', '$2a$10$z2X8z6Q6z6Q6z6Q6z6Q6zux6z6Q6z6Q6z6Q6z6Q6z6Q6z6Q6z6Q', 'admin@example.com', 'Admin', 'User', 'ADMIN'),
    ('user', '$2a$10$y2X8y6Q6y6Q6y6Q6y6Q6yuy6y6Q6y6Q6y6Q6y6Q6y6Q6y6Q6y6Q', 'user@example.com', 'Regular', 'User', 'USER');